# Generated by Django 5.1.2 on 2024-10-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('parameters', models.JSONField()),
                ('body', models.TextField()),
                ('headers', models.JSONField()),
            ],
        ),
    ]
